services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:v3.7.0
    container_name: 3x-ui
    hostname: 3x-ui
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    restart: unless-stopped
    ports:
      - "20530:2053"
      - "443:443/tcp"
      - "443:443/udp"